# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1
  - nightly
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python-pip   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user sklearn           ; fi
notifications:
  email: false

codecov: true
coveralls: true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
