# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
addons:
  apt:
    packages:
      - python3-pip
      - python3-numpy
      - python3-setuptools 
matrix:
  include:
    - python:3.6
julia:
  - 1
  - nightly
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install --user sklearn           ; fi
notifications:
  email: false

codecov: true
coveralls: true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
