# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
env:
  global:
  - PYTHON=Conda
julia:
  - 1
  - nightly
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then conda install -q -y scikit-learn
notifications:
  email: false

codecov: true
coveralls: true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
