# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
env:
  global:
  - PYTHON=Conda
julia:
  - 1
  - nightly
notifications:
  email: false

codecov: true
coveralls: true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
